/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import VectorImage from 'src/assets/images/Adminpages_Vector.png';
import Vector1Image from 'src/assets/images/Adminpages_Vector_1.png';
import Ellipse1Image from 'src/assets/images/Adminpages_Ellipse_1.png';
import Ellipse3Image from 'src/assets/images/Adminpages_Ellipse_3.png';
import Ellipse4Image from 'src/assets/images/Adminpages_Ellipse_4.png';
import Ellipse5Image from 'src/assets/images/Adminpages_Ellipse_5.png';
import { styled } from '@mui/material/styles';
import NavBar from 'src/components/NavBar/NavBar';

const AdminPages1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `695px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Dashboard = styled('div')({
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  width: `826.78px`,
  height: `479.75px`,
  position: `absolute`,
  left: `262px`,
  top: `77px`,
});

const RecentSchoolAtendanc = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(30, 58, 138, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `24.577293395996094px`,
  letterSpacing: `1.2288646697998047px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  position: `absolute`,
  left: `283px`,
  top: `285px`,
}));

const Frame63 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 0px 1.9661835432052612px rgba(0, 0, 0, 0.2)`,
  borderRadius: `10.814009666442871px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `19.661834716796875px 0.9830917716026306px`,
  boxSizing: `border-box`,
  width: `264.45px`,
  height: `181.87px`,
  left: `558px`,
  top: `88px`,
  overflow: `hidden`,
});

const Frame68 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Frame48 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const YesterdayAttendance = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(30, 58, 138, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
}));

const Frame67 = styled('div')({
  border: `1px solid rgba(39, 72, 149, 1)`,
  boxSizing: `border-box`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `9.830917358398438px 13.763284683227539px 1.9661835432052612px 7.864734172821045px`,
  margin: `23.594202041625977px 0px 0px 0px`,
});

const Rectangle81 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(96, 165, 250, 1)`,
  width: `17.7px`,
  height: `29.49px`,
  margin: `0px`,
}));

const Rectangle79 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(30, 58, 138, 0.8)`,
  width: `23.59px`,
  height: `63.9px`,
  margin: `0px 0px 0px 7.864734172821045px`,
}));

const Rectangle83 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(96, 165, 250, 1)`,
  width: `18.68px`,
  height: `16.71px`,
  margin: `0px 0px 0px 7.864734172821045px`,
}));

const Rectangle82 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(30, 58, 138, 0.8)`,
  width: `23.59px`,
  height: `82.58px`,
  margin: `0px 0px 0px 7.864734172821045px`,
}));

const Frame64 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 0px 1.9661835432052612px rgba(0, 0, 0, 0.2)`,
  borderRadius: `10.814009666442871px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `19.661834716796875px 6.8816423416137695px`,
  boxSizing: `border-box`,
  width: `264.45px`,
  height: `181.87px`,
  left: `855px`,
  top: `85px`,
  overflow: `hidden`,
});

const Frame481 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 10.814009666442871px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const SchoolAvg = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(30, 58, 138, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
}));

const Vector = styled('img')({
  height: `105px`,
  width: `182px`,
  margin: `9.830917358398438px 0px 0px 0px`,
});

const Frame62 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 0px 1.9661835432052612px rgba(0, 0, 0, 0.2)`,
  borderRadius: `10.814009666442871px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `19.661834716796875px 0.9830917716026306px`,
  boxSizing: `border-box`,
  width: `264.45px`,
  height: `181.87px`,
  left: `262px`,
  top: `85px`,
  overflow: `hidden`,
});

const Frame61 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px 5.898550510406494px`,
  boxSizing: `border-box`,
  height: `122.89px`,
  width: `223.16px`,
  margin: `0px`,
});

const Frame482 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const SchoolPartner = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(30, 58, 138, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
}));

const IcSharpNotificationI = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `23.59px`,
  height: `23.59px`,
  margin: `0px 0px 0px 45.22222137451172px`,
  overflow: `hidden`,
});

const Vector1 = styled('img')({
  height: `21.14px`,
  width: `17.7px`,
  position: `absolute`,
  left: `3px`,
  top: `1px`,
});

const Frame60 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 2.949275255203247px`,
  boxSizing: `border-box`,
  margin: `58.00241470336914px 0px 0px 0px`,
});

const Group1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `129.77px`,
  height: `60.95px`,
  margin: `0px`,
});

const Ellipse1 = styled('img')({
  height: `60.95px`,
  width: `59.97px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Ellipse3 = styled('img')({
  height: `60.95px`,
  width: `59.97px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `33px`,
  top: `0px`,
});

const Ellipse4 = styled('img')({
  height: `60.95px`,
  width: `59.97px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `70px`,
  top: `0px`,
});

const Frame47 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(30, 58, 138, 1)`,
  borderRadius: `16.712560653686523px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `9.830917358398438px`,
  boxSizing: `border-box`,
  width: `75.7px`,
  height: `41.29px`,
  margin: `0px`,
}));

const Others = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame89 = styled('div')({
  boxShadow: `0px 0px 2.949275255203247px rgba(0, 0, 0, 0.25)`,
  border: `0.19661836326122284px solid rgba(242, 239, 239, 1)`,
  boxSizing: `border-box`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `22.61111068725586px 0px`,
  left: `262px`,
  top: `337px`,
});

const Frame83 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 33.42512130737305px 0px 24.577293395996094px`,
  boxSizing: `border-box`,
  height: `29.49px`,
  width: `876.92px`,
  margin: `0px`,
});

const Frame82 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Frame81 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Frame80 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Name = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(30, 58, 138, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `17.69565200805664px`,
  letterSpacing: `0.8847826004028321px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
}));

const Frame79 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 81.59661865234375px`,
});

const Present = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(30, 58, 138, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `17.69565200805664px`,
  letterSpacing: `0.8847826004028321px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
}));

const Absent = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(30, 58, 138, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `17.69565200805664px`,
  letterSpacing: `0.8847826004028321px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 40.3067626953125px`,
}));

const Percent = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(30, 58, 138, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `17.69565200805664px`,
  letterSpacing: `0.8847826004028321px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 35.39130401611328px`,
}));

const DAte = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(30, 58, 138, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `17.69565200805664px`,
  letterSpacing: `0.8847826004028321px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 91.42753601074219px`,
}));

const Others1 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(30, 58, 138, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `17.69565200805664px`,
  letterSpacing: `0.8847826004028321px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 121.90338134765625px`,
}));

const Frame88 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `10px 0px 0px 0px`,
});

const Frame84 = styled('div')({
  backgroundColor: `rgba(196, 208, 236, 0.6)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 0px 0px 2.949275255203247px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const IdaTech = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
});

const Q120 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 80.613525390625px`,
});

const Q30 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 80.613525390625px`,
});

const Q70 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 80.613525390625px`,
});

const Q30032023 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 80.613525390625px`,
});

const Frame78 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 80.613525390625px`,
});

const Frame77 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(59, 130, 246, 1)`,
  borderRadius: `8.84782600402832px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `9.830917358398438px`,
  boxSizing: `border-box`,
  width: `43.26px`,
  height: `31.46px`,
  margin: `0px`,
}));

const Edit = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `900`,
  fontSize: `17.69565200805664px`,
  letterSpacing: `0.8847826004028321px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame75 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(96, 165, 250, 1)`,
  borderRadius: `7.864734172821045px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `9.830917358398438px`,
  boxSizing: `border-box`,
  width: `65.87px`,
  height: `31.46px`,
  margin: `0px 0px 0px 10.814009666442871px`,
}));

const Delete = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame76 = styled('div')({
  borderRadius: `7.864734172821045px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `9.830917358398438px`,
  boxSizing: `border-box`,
  width: `65.87px`,
  height: `31.46px`,
  margin: `0px 0px 0px 10.814009666442871px`,
});

const Details = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(59, 130, 246, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
}));

const Frame85 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 0px 0px 2.949275255203247px`,
  boxSizing: `border-box`,
  margin: `24.577293395996094px 0px 0px 0px`,
});

const GirlsCode = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
});

const Q600 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 79.63043212890625px`,
});

const Q12 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 79.63043212890625px`,
});

const Q90 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 79.63043212890625px`,
});

const Q01042023 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 79.63043212890625px`,
});

const Frame781 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 79.63043212890625px`,
});

const Frame771 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(59, 130, 246, 1)`,
  borderRadius: `8.84782600402832px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `9.830917358398438px`,
  boxSizing: `border-box`,
  width: `43.26px`,
  height: `31.46px`,
  margin: `0px`,
}));

const Edit1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `900`,
  fontSize: `17.69565200805664px`,
  letterSpacing: `0.8847826004028321px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame751 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(96, 165, 250, 1)`,
  borderRadius: `7.864734172821045px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `9.830917358398438px`,
  boxSizing: `border-box`,
  width: `65.87px`,
  height: `31.46px`,
  margin: `0px 0px 0px 10.814009666442871px`,
}));

const Delete1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame761 = styled('div')({
  borderRadius: `7.864734172821045px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `9.830917358398438px`,
  boxSizing: `border-box`,
  width: `65.87px`,
  height: `31.46px`,
  margin: `0px 0px 0px 10.814009666442871px`,
});

const Details1 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(59, 130, 246, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
}));

const Frame86 = styled('div')({
  backgroundColor: `rgba(196, 208, 236, 0.61)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 0px 0px 2.949275255203247px`,
  boxSizing: `border-box`,
  margin: `24.577293395996094px 0px 0px 0px`,
});

const IprcHuye = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
});

const Q212 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 80.613525390625px`,
});

const Q3 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 80.613525390625px`,
});

const Q96 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 80.613525390625px`,
});

const Q30042023 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 80.613525390625px`,
});

const Frame782 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 80.613525390625px`,
});

const Frame772 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(59, 130, 246, 1)`,
  borderRadius: `8.84782600402832px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `9.830917358398438px`,
  boxSizing: `border-box`,
  width: `43.26px`,
  height: `31.46px`,
  margin: `0px`,
}));

const Edit2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `900`,
  fontSize: `17.69565200805664px`,
  letterSpacing: `0.8847826004028321px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame752 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(96, 165, 250, 1)`,
  borderRadius: `7.864734172821045px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `9.830917358398438px`,
  boxSizing: `border-box`,
  width: `65.87px`,
  height: `31.46px`,
  margin: `0px 0px 0px 10.814009666442871px`,
}));

const Delete2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame762 = styled('div')({
  borderRadius: `7.864734172821045px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `9.830917358398438px`,
  boxSizing: `border-box`,
  width: `65.87px`,
  height: `31.46px`,
  margin: `0px 0px 0px 10.814009666442871px`,
});

const Details2 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(59, 130, 246, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
}));

const Frame87 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 0px 0px 2.949275255203247px`,
  boxSizing: `border-box`,
  margin: `24.577293395996094px 0px 0px 0px`,
});

const GsKagarama = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  width: `92.41px`,
  margin: `0px`,
});

const Q80 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 79.63043212890625px`,
});

const Q10 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 79.63043212890625px`,
});

const Q97 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 79.63043212890625px`,
});

const Q3052023 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px 0px 0px 79.63043212890625px`,
});

const Frame783 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 79.63043212890625px`,
});

const Frame773 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(59, 130, 246, 1)`,
  borderRadius: `8.84782600402832px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `9.830917358398438px`,
  boxSizing: `border-box`,
  width: `43.26px`,
  height: `31.46px`,
  margin: `0px`,
}));

const Edit3 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `900`,
  fontSize: `17.69565200805664px`,
  letterSpacing: `0.8847826004028321px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame753 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(96, 165, 250, 1)`,
  borderRadius: `7.864734172821045px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `9.830917358398438px`,
  boxSizing: `border-box`,
  width: `65.87px`,
  height: `31.46px`,
  margin: `0px 0px 0px 10.814009666442871px`,
}));

const Delete3 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame763 = styled('div')({
  borderRadius: `7.864734172821045px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `9.830917358398438px`,
  boxSizing: `border-box`,
  width: `65.87px`,
  height: `31.46px`,
  margin: `0px 0px 0px 10.814009666442871px`,
});

const Details3 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(59, 130, 246, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14.746376991271973px`,
  letterSpacing: `0.7373188495635986px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  margin: `0px`,
}));

const Rectangle98 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 0.9)`,
  border: `0.4915458858013153px solid rgba(183, 175, 175, 1)`,
  boxSizing: `border-box`,
  width: `12.78px`,
  height: `18.68px`,
  position: `absolute`,
  left: `263px`,
  top: `463px`,
});

const Rectangle101 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 0.9)`,
  border: `0.4915458858013153px solid rgba(183, 175, 175, 1)`,
  boxSizing: `border-box`,
  width: `12.78px`,
  height: `18.68px`,
  position: `absolute`,
  left: `263px`,
  top: `518px`,
});

const Rectangle99 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 0.9)`,
  border: `0.4915458858013153px solid rgba(183, 175, 175, 1)`,
  boxSizing: `border-box`,
  width: `12.78px`,
  height: `18.68px`,
  position: `absolute`,
  left: `263px`,
  top: `406px`,
});

const Rectangle100 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 0.9)`,
  border: `0.4915458858013153px solid rgba(183, 175, 175, 1)`,
  boxSizing: `border-box`,
  width: `12.78px`,
  height: `18.68px`,
  position: `absolute`,
  left: `262px`,
  top: `577px`,
});

const Frame98 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(30, 58, 138, 1)`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `950px`,
  height: `56px`,
  left: `230px`,
  top: `641px`,
}));

const CopyrightIDaTechnolo = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `300`,
  fontSize: `21.821882247924805px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Prev = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(30, 58, 138, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0.75px`,
  textDecoration: `underline`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  position: `absolute`,
  left: `894px`,
  top: `307px`,
}));

const Q1 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(30, 58, 138, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0.75px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  position: `absolute`,
  left: `950px`,
  top: `307px`,
}));

const Q2 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(30, 58, 138, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0.75px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  position: `absolute`,
  left: `976px`,
  top: `307px`,
}));

const Q31 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(30, 58, 138, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0.75px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  position: `absolute`,
  left: `1002px`,
  top: `307px`,
}));

const Q4 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(30, 58, 138, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0.75px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  position: `absolute`,
  left: `1028px`,
  top: `307px`,
}));

const Next = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(30, 58, 138, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `15px`,
  letterSpacing: `0.75px`,
  textDecoration: `underline`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  position: `absolute`,
  left: `1070px`,
  top: `307px`,
}));

const IgaTeam = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(30, 58, 138, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `800`,
  fontSize: `19.661834716796875px`,
  letterSpacing: `0.9830917358398438px`,
  textDecoration: `none`,
  lineHeight: `129.99999523162842%`,
  textTransform: `none`,
  position: `absolute`,
  left: `303px`,
  top: `20px`,
}));

const Ellipse5 = styled('img')({
  height: `60.95px`,
  width: `59.97px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `1088px`,
  top: `7px`,
});

const NavBar1 = styled(NavBar)(({ theme }) => ({
  width: `230.04px`,
  height: `664.57px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

function AdminPages(props) {
  return (
    <AdminPages1 className={props.className}>
      <Dashboard></Dashboard>
      <RecentSchoolAtendanc>{`Recent school atendance`}</RecentSchoolAtendanc>
      <Frame63>
        <Frame68>
          <Frame48>
            <YesterdayAttendance>{`yesterday attendance`}</YesterdayAttendance>
          </Frame48>
          <Frame67>
            <Rectangle81></Rectangle81>
            <Rectangle79></Rectangle79>
            <Rectangle83></Rectangle83>
            <Rectangle82></Rectangle82>
          </Frame67>
        </Frame68>
      </Frame63>
      <Frame64>
        <Frame481>
          <SchoolAvg>{`School Avg`}</SchoolAvg>
        </Frame481>
        <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
      </Frame64>
      <Frame62>
        <Frame61>
          <Frame482>
            <SchoolPartner>{`School partner`}</SchoolPartner>
            <IcSharpNotificationI>
              <Vector1 src={Vector1Image} loading="lazy" alt={'Vector'} />
            </IcSharpNotificationI>
          </Frame482>
          <Frame60>
            <Group1>
              <Ellipse1 src={Ellipse1Image} loading="lazy" alt={'Ellipse 1'} />
              <Ellipse3 src={Ellipse3Image} loading="lazy" alt={'Ellipse 3'} />
              <Ellipse4 src={Ellipse4Image} loading="lazy" alt={'Ellipse 4'} />
            </Group1>
            <Frame47>
              <Others>{`Others`}</Others>
            </Frame47>
          </Frame60>
        </Frame61>
      </Frame62>
      <Frame89>
        <Frame83>
          <Frame82>
            <Frame81>
              <Frame80>
                <Name>{`Name`}</Name>
                <Frame79>
                  <Present>{`Present`}</Present>
                  <Absent>{`Absent`}</Absent>
                </Frame79>
              </Frame80>
              <Percent>{`Percent`}</Percent>
            </Frame81>
            <DAte>{`DAte`}</DAte>
          </Frame82>
          <Others1>{`Others`}</Others1>
        </Frame83>
        <Frame88>
          <Frame84>
            <IdaTech>{`Ida Tech`}</IdaTech>
            <Q120>{`120`}</Q120>
            <Q30>{`30`}</Q30>
            <Q70>{`70%`}</Q70>
            <Q30032023>{`30/03/2023`}</Q30032023>
            <Frame78>
              <Frame77>
                <Edit>{`Edit`}</Edit>
              </Frame77>
              <Frame75>
                <Delete>{`Delete`}</Delete>
              </Frame75>
              <Frame76>
                <Details>{`Details`}</Details>
              </Frame76>
            </Frame78>
          </Frame84>
          <Frame85>
            <GirlsCode>{`Girls code`}</GirlsCode>
            <Q600>{`600`}</Q600>
            <Q12>{`12`}</Q12>
            <Q90>{`90%`}</Q90>
            <Q01042023>{`01/04/2023`}</Q01042023>
            <Frame781>
              <Frame771>
                <Edit1>{`Edit`}</Edit1>
              </Frame771>
              <Frame751>
                <Delete1>{`Delete`}</Delete1>
              </Frame751>
              <Frame761>
                <Details1>{`Details`}</Details1>
              </Frame761>
            </Frame781>
          </Frame85>
          <Frame86>
            <IprcHuye>{`IPRC Huye`}</IprcHuye>
            <Q212>{`212`}</Q212>
            <Q3>{`3`}</Q3>
            <Q96>{`96%`}</Q96>
            <Q30042023>{`30/04/2023`}</Q30042023>
            <Frame782>
              <Frame772>
                <Edit2>{`Edit`}</Edit2>
              </Frame772>
              <Frame752>
                <Delete2>{`Delete`}</Delete2>
              </Frame752>
              <Frame762>
                <Details2>{`Details`}</Details2>
              </Frame762>
            </Frame782>
          </Frame86>
          <Frame87>
            <GsKagarama>{`Gs kagarama`}</GsKagarama>
            <Q80>{`80`}</Q80>
            <Q10>{`10`}</Q10>
            <Q97>{`97%`}</Q97>
            <Q3052023>{`3/05/2023`}</Q3052023>
            <Frame783>
              <Frame773>
                <Edit3>{`Edit`}</Edit3>
              </Frame773>
              <Frame753>
                <Delete3>{`Delete`}</Delete3>
              </Frame753>
              <Frame763>
                <Details3>{`Details`}</Details3>
              </Frame763>
            </Frame783>
          </Frame87>
        </Frame88>
      </Frame89>
      <Rectangle98></Rectangle98>
      <Rectangle101></Rectangle101>
      <Rectangle99></Rectangle99>
      <Rectangle100></Rectangle100>
      <Frame98>
        <CopyrightIDaTechnolo>
          {`© Copyright iDa Technology.Kicukiro- KK 15 Rd, Kigali, Rwanda . All Rights Reserved`}
        </CopyrightIDaTechnolo>
      </Frame98>
      <Prev>{`Prev`}</Prev>
      <Q1>{`1`}</Q1>
      <Q2>{`2`}</Q2>
      <Q31>{`3`}</Q31>
      <Q4>{`4`}</Q4>
      <Next>{`Next`}</Next>
      <IgaTeam>{`IGA team`}</IgaTeam>
      <Ellipse5 src={Ellipse5Image} loading="lazy" alt={'Ellipse 5'} />
      <NavBar1 />
    </AdminPages1>
  );
}

export default AdminPages;
